package com.herath.corexo.core.utils;

public interface CorexoCoreConstants {
	String GENERIC_EXCEPTION_MSG = "An exception occured whiel processing.";
	String COREXO_MESSAGE_BOX_MANAGERS_LIST = "COREXO_MESSAGE_BOX_MANAGERS_LIST";
	String DEFAULT_SEND_MESSAGE_BOX = "DEFAULT_SEND_MESSAGE_BOX";
	String DEFAULT_ASK_MESSAGE_BOX = "DEFAULT_ASK_MESSAGE_BOX";
	String DEFAULT_PREFIX_ID_GENERATOR = "DEFAULT_PREFIX_ID_GENERATOR";
	String DEFAULT_SUFFIX_ID_GENERATOR = "DEFAULT_SUFFIX_ID_GENERATOR";

	String ID_GENERATOR_HOLDER_MAP = "ID_GENERATOR_HOLDER_MAP";
	String DEFAULT_ID_GENERATOR_HOLDER = "DEFAULT_ID_GENERATOR_HOLDER";
	String DEFAULT_MESSAGE_PREFIX = "COREXO-MESSAGE-ID";
	String HYPHEN = "-";
}
